f = open('C:/Users/Administrator/Desktop/py.txt','r+')
f.write('写数据到文件')
f.close()
y = open('C:/Users/Administrator/Desktop/py.txt','r')
str1=y.readline()
str2=y.read()
print(str2)
print(str1)
y.close()